"""S05B Phase 2: forecast pathology.

OBSTRUCTION (reported, not worked around): S05 persisted no forecast
artifacts. `partde.py` holds F in memory and writes only s05_metrics.csv
and s05_mcs.csv. Phase 2's premise ("reads S05 forecast artifacts only")
cannot be satisfied. Forecasts are therefore regenerated by calling S05's
own `partde.build_series` / `partde.forecasts` unmodified on S05's stored
panels. Part D is deterministic (fixed OLS refit schedule, fixed-start
Nelder-Mead, no RNG), so the regenerated forecasts are the same objects
S05 scored; S05A Phase 4 verified this class of regeneration reproduces
S05's QLIKE column bitwise. Nothing is written outside S05B.
"""

import json
import os
import sys
import time
from concurrent.futures import ProcessPoolExecutor, as_completed

import numpy as np
import pandas as pd

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.dirname(os.path.dirname(BASE))
RES = os.path.join(BASE, "results")
CACHE = os.path.join(RES, "cache")
S05 = os.path.join(ROOT, "sessions", "s05-reliability-mcs")
S05_RES = os.path.join(S05, "results")
sys.path.insert(0, os.path.join(S05, "src"))
import partde as pd5                                    # noqa: E402

MODELS = pd5.MODELS
GROUPS = [(r, g, b, h) for g in ["GLOBEX", "RTH"] for r in ["ES", "NQ"]
          for b in ["B0", "B1"] for h in ["1day", "1h", "30min"]]
WLEN = {"1day": None, "1h": 60, "30min": 30}


def regen(job):
    root, geom, btag, horizon = job
    t0 = time.time()
    z = np.load(os.path.join(S05_RES, f"panel_{root}_{geom}_{btag}.npz"))
    grid = z["logpx"].astype(np.float64)
    dates = np.array(z["dates"], dtype="U10")
    S = pd5.build_series(grid, WLEN[horizon])
    D = S["nw"]
    warm = 500 if horizon == "1day" else max(500, 22 * D + 100)
    refit = 1 if horizon == "1day" else D
    F, start, nonconv = pd5.forecasts(S, D, warm, refit, horizon == "1day")
    rv = S["rv"]
    ok = np.ones(len(rv), bool)
    for m in MODELS:
        ok &= np.isfinite(F[m])
    ok[:max(start, warm)] = False
    wdates = np.repeat(dates, D)[:len(rv)]
    out = os.path.join(CACHE, f"fc_{root}_{geom}_{btag}_{horizon}.npz")
    np.savez_compressed(
        out, rv=rv, bv=S["bv"], rq=S["rq"], ret=S["ret"],
        park=S["park"], gk=S["gk"], ok=ok, wdates=wdates, D=D,
        start=start, warm=warm, refit=refit, nonconv=nonconv,
        **{f"F_{m}": F[m] for m in MODELS})
    return dict(group=f"{root}/{geom}/{btag}/{horizon}", n_windows=int(len(rv)),
                n_evaluated=int(ok.sum()), D=int(D), start=int(start),
                warm=int(warm), m5_nonconv=int(nonconv),
                seconds=round(time.time() - t0, 1))


def main():
    t0 = time.time()
    os.makedirs(CACHE, exist_ok=True)
    todo = [g for g in GROUPS
            if not os.path.exists(os.path.join(
                CACHE, f"fc_{g[0]}_{g[1]}_{g[2]}_{g[3]}.npz"))]
    print(f"regenerating {len(todo)} of {len(GROUPS)} groups", flush=True)
    meta = []
    with ProcessPoolExecutor(max_workers=6) as ex:
        futs = {ex.submit(regen, g): g for g in todo}
        for f in as_completed(futs):
            meta.append(f.result())
            print(f"  {len(meta)}/{len(todo)} {meta[-1]['group']} "
                  f"({meta[-1]['seconds']}s)", flush=True)
    with open(os.path.join(RES, "phase2_regen_meta.json"), "w") as fh:
        json.dump(dict(groups=meta, total_seconds=round(time.time() - t0, 1),
                       note="S05 persisted no forecasts; regenerated with "
                            "partde.build_series/forecasts unmodified"),
                  fh, indent=1)
    print(f"PHASE2 REGEN DONE {time.time()-t0:.0f}s", flush=True)


if __name__ == "__main__":
    main()
