"""S05B Phases 3 and 4: panel materialization, non-finite audit, grid cache.

Phase 3 reads the S05 log-price panels once and caches one-minute returns
plus an exact data-presence mask (regenerated by calling S03's
`analysis.build_panels` on the S04 repaired bars, the same function that
built the panels). Phase 4 builds every derived quantity the later phases
need, off that cache, in one pass.

Sub-bar construction (documented, applies everywhere in S05B): within a
window of L one-minute returns, sub-bar j spans return indices
[floor(j*L/M), floor((j+1)*L/M)). Sub-bar returns are sums of one-minute
returns, i.e. differences of the log price at the group endpoints. When
M does not divide L the group sizes differ by at most one; that stub is
counted and reported rather than hidden.
"""

import json
import os
import sys
import time

import numpy as np
import pandas as pd
from scipy.special import polygamma

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.dirname(os.path.dirname(BASE))
RES = os.path.join(BASE, "results")
CACHE = os.path.join(RES, "cache")
S05_RES = os.path.join(ROOT, "sessions", "s05-reliability-mcs", "results")
S04_RES = os.path.join(ROOT, "sessions", "s04-repairs-diagnostics",
                       "results")
sys.path.insert(0, os.path.join(ROOT, "sessions", "s03-data-noise", "src"))
sys.path.insert(0, os.path.join(ROOT, "sessions", "s05-reliability-mcs",
                                "src"))
import analysis as s03a                                  # noqa: E402
import partde as pd5                                     # noqa: E402
from parta import quart_suite                            # noqa: E402

MODELS = pd5.MODELS
# horizon -> window length in one-minute returns
HORIZ = {"1day": None, "1h": 60, "30min": 30}
# Phase 4 extended grids (session length in minutes -> M list)
GRID = {
    ("RTH", "1day"): [5, 6, 10, 13, 26, 78, 195, 390],
    ("RTH", "1h"): [4, 5, 6, 10, 12, 15, 20, 30, 60],
    ("RTH", "30min"): [5, 6, 10, 15, 30],
    ("GLOBEX", "1day"): [5, 6, 10, 12, 23, 46, 138, 345, 1380],
}
SESSION_MIN = {("RTH", "1day"): 390, ("RTH", "1h"): 60,
               ("RTH", "30min"): 30, ("GLOBEX", "1day"): 1380}
CELLS = [(r, g, b) for g in ["GLOBEX", "RTH"] for r in ["ES", "NQ"]
         for b in ["B0", "B1"]]
QVARIANTS = ["RQ_RV", "TQ_BV", "TRQ3_TRV3", "TRQ5_TRV5", "TRQ10_TRV10",
             "MEDRQ_MEDRV"]


def trigamma(x):
    return polygamma(1, x)


def windows(r1, wlen):
    """(sessions, L) one-minute returns -> (nwindows, wlen)."""
    if wlen is None:
        return r1, 1
    nw = r1.shape[1] // wlen
    return r1[:, :nw * wlen].reshape(-1, wlen), nw


def subbars(rw, M):
    """Aggregate (N, L) one-minute returns into (N, M) sub-bar returns."""
    N, L = rw.shape
    edges = (np.arange(M + 1) * L) // M
    cs = np.concatenate([np.zeros((N, 1)), np.cumsum(rw, axis=1)], axis=1)
    return cs[:, edges[1:]] - cs[:, edges[:-1]], np.diff(edges)


def load_present():
    """Exact presence mask per (root, geom), regenerated from S04 bars."""
    out = {}
    for geom in ["GLOBEX", "RTH"]:
        df = pd.read_parquet(os.path.join(S04_RES, f"bars_{geom}.parquet"))
        for root in ["ES", "NQ"]:
            fn = os.path.join(CACHE, f"present_{root}_{geom}.npz")
            if os.path.exists(fn):
                out[(root, geom)] = np.load(fn)["present"]
                continue
            dates, filled, present = s03a.build_panels(df, root, geom)
            np.savez_compressed(fn, present=present,
                                dates=dates.astype("datetime64[D]")
                                .astype(str))
            out[(root, geom)] = present
    return out


def main():
    t0 = time.time()
    os.makedirs(CACHE, exist_ok=True)
    timers = {}

    # ---------------- Phase 3: read panels once, cache returns
    t = time.time()
    R1, DATES, YEARS = {}, {}, {}
    for root, geom, btag in CELLS:
        z = np.load(os.path.join(S05_RES, f"panel_{root}_{geom}_{btag}.npz"))
        g = z["logpx"].astype(np.float64)
        r1 = np.diff(g, axis=1)
        R1[(root, geom, btag)] = r1
        d = pd.to_datetime(np.array(z["dates"], dtype="U10"))
        DATES[(root, geom, btag)] = d
        YEARS[(root, geom, btag)] = d.year.values
        np.savez_compressed(
            os.path.join(CACHE, f"ret1m_{root}_{geom}_{btag}.npz"),
            r1=r1.astype(np.float32),
            dates=np.array(z["dates"], dtype="U10"))
    timers["p3_panel_cache"] = round(time.time() - t, 1)

    t = time.time()
    PRESENT = load_present()
    timers["p3_present_masks"] = round(time.time() - t, 1)

    # ---------------- Phase 3 audit: zero / tiny RV by horizon and year
    t = time.time()
    zero_rows = []
    for (root, geom, btag), r1 in R1.items():
        yrs = YEARS[(root, geom, btag)]
        for hname, wlen in HORIZ.items():
            rw, nw = windows(r1, wlen)
            rv = (rw ** 2).sum(axis=1)
            wyears = np.repeat(yrs, nw)
            for y in sorted(set(yrs.tolist())) + [0]:
                m = (wyears == y) if y else np.ones(len(rv), bool)
                n = int(m.sum())
                if not n:
                    continue
                zero_rows.append(dict(
                    root=root, geom=geom, btag=btag, horizon=hname,
                    year=int(y), n_windows=n,
                    n_rv_exact_zero=int((rv[m] == 0).sum()),
                    share_rv_exact_zero=float((rv[m] == 0).mean()),
                    n_rv_lt_1e14=int((rv[m] < 1e-14).sum()),
                    share_rv_lt_1e14=float((rv[m] < 1e-14).mean()),
                    min_rv=float(rv[m].min())))
    pd.DataFrame(zero_rows).to_csv(
        os.path.join(RES, "phase3_zero_rv.csv"), index=False)

    # ---------------- Phase 3: quarticity variants zero counts
    qrows = []
    for (root, geom, btag), r1 in R1.items():
        for hname, wlen in HORIZ.items():
            rw, nw = windows(r1, wlen)
            L = rw.shape[1]
            for M in ([m for m in GRID.get((geom, hname), []) if m <= L]
                      or []):
                sb, sizes = subbars(rw, M)
                if M < 3:
                    continue
                q = quart_suite(sb, M)
                for var in QVARIANTS:
                    Q, P = q[var]
                    qrows.append(dict(
                        root=root, geom=geom, btag=btag, horizon=hname,
                        M=M, variant=var, n=len(Q),
                        n_Q_zero=int((Q == 0).sum()),
                        n_Q_lt_1e14=int((Q < 1e-14).sum()),
                        n_P_zero=int((P == 0).sum()),
                        n_P_lt_1e14=int((P < 1e-14).sum()),
                        min_Q=float(Q.min()), min_P=float(P.min())))
    pd.DataFrame(qrows).to_csv(
        os.path.join(RES, "phase3_quarticity_zeros.csv"), index=False)
    timers["p3_zero_audit"] = round(time.time() - t, 1)

    # ---------------- Phase 3: infinite-QLIKE windows (needs forecasts)
    t = time.time()
    inf_rows, inf_detail = [], []
    for root, geom, btag in CELLS:
        for hname in ["1day", "1h", "30min"]:
            fn = os.path.join(CACHE, f"fc_{root}_{geom}_{btag}_{hname}.npz")
            if not os.path.exists(fn):
                continue
            z = np.load(fn)
            rv, ok = z["rv"], z["ok"]
            D = int(z["D"])
            wdates = np.array(z["wdates"], dtype="U10")
            widx = np.tile(np.arange(D), len(rv) // D + 1)[:len(rv)]
            for m in MODELS:
                F = z[f"F_{m}"]
                ql = np.where(ok, pd5.qlike(np.where(ok, F, 1.0),
                                            np.where(ok, rv, 1.0)), np.nan)
                bad = ok & ~np.isfinite(ql)
                inf_rows.append(dict(
                    root=root, geom=geom, btag=btag, horizon=hname,
                    model=m, n_eval=int(ok.sum()),
                    n_nonfinite_qlike=int(bad.sum()),
                    n_rv_zero_in_eval=int((ok & (rv == 0)).sum())))
                if bad.any() and geom == "GLOBEX" and hname in ("1h",
                                                                "30min"):
                    for i in np.where(bad)[0][:200]:
                        wl = HORIZ[hname]
                        start_min = int(widx[i]) * wl
                        inf_detail.append(dict(
                            root=root, geom=geom, btag=btag, horizon=hname,
                            model=m, window_index=int(i),
                            session_date=str(wdates[i]),
                            window_in_session=int(widx[i]),
                            window_start_min_from_1800NY=start_min,
                            ny_clock=f"{(18*60+start_min)//60%24:02d}:"
                                     f"{(18*60+start_min)%60:02d}",
                            overnight=bool(start_min < 930),
                            rv=float(rv[i]), forecast=float(F[i])))
    pd.DataFrame(inf_rows).to_csv(
        os.path.join(RES, "phase3_nonfinite_qlike.csv"), index=False)
    pd.DataFrame(inf_detail).to_csv(
        os.path.join(RES, "phase3_nonfinite_detail.csv"), index=False)
    timers["p3_nonfinite"] = round(time.time() - t, 1)

    # ---------------- Phase 3: reconstruct three named loss arrays
    t = time.time()
    named = [("ES", "GLOBEX", "B0", "1h", "S-A"),
             ("ES", "GLOBEX", "B0", "30min", "S-C_q0.80"),
             ("ES", "RTH", "B0", "1day", "S-A")]
    MET = pd.read_csv(os.path.join(S05_RES, "s05_metrics.csv"))
    loss_rows = []
    for root, geom, btag, hname, scheme in named:
        fn = os.path.join(CACHE, f"fc_{root}_{geom}_{btag}_{hname}.npz")
        if not os.path.exists(fn):
            continue
        z = np.load(fn)
        rv, ok = z["rv"], z["ok"]
        rvv = rv[ok]
        Fm = {m: z[f"F_{m}"][ok] for m in MODELS}
        L = np.column_stack([pd5.qlike(Fm[m], rvv) for m in MODELS])
        if scheme == "S-A":
            mask = np.ones(len(rvv), bool)
        else:
            q = float(scheme.split("_q")[1])
            base = rvv if scheme.startswith("S-B") else Fm["M2_HAR"]
            mask = base > np.quantile(base, q)
        Ls = L[mask]
        sub = MET[(MET.root == root) & (MET.geom == geom)
                  & (MET.btag == btag) & (MET.horizon == hname)
                  & (MET.scheme == scheme)]
        for j, m in enumerate(MODELS):
            col = Ls[:, j]
            s05q = float(sub[sub.model == m]["qlike_mean"].iloc[0])
            loss_rows.append(dict(
                cell=f"{root}/{geom}/{btag}/{hname}/{scheme}",
                shape=f"{Ls.shape[0]}x{Ls.shape[1]}", model=m,
                n_nonfinite=int((~np.isfinite(col)).sum()),
                n_inf=int(np.isinf(col).sum()),
                n_nan=int(np.isnan(col).sum()),
                col_mean=float(col.mean()),
                col_mean_finite_only=float(col[np.isfinite(col)].mean())
                if np.isfinite(col).any() else np.nan,
                s05_qlike_mean=s05q,
                matches_s05=bool((np.isnan(col.mean()) and np.isnan(s05q))
                                 or col.mean() == s05q)))
    pd.DataFrame(loss_rows).to_csv(
        os.path.join(RES, "phase3_named_loss_arrays.csv"), index=False)
    timers["p3_named_arrays"] = round(time.time() - t, 1)

    # ---------------- Phase 4: grid cache
    t = time.time()
    grid_rows = []
    for root, geom, btag in CELLS:
        r1 = R1[(root, geom, btag)]
        pres = PRESENT[(root, geom)]
        pres_r = pres[:, 1:] & pres[:, :-1]        # a return needs both ends
        yrs = YEARS[(root, geom, btag)]
        for (g2, hname), Ms in GRID.items():
            if g2 != geom:
                continue
            wlen = HORIZ[hname]
            rw, nw = windows(r1, wlen)
            pw, _ = windows(pres_r.astype(np.float64), wlen)
            L = rw.shape[1]
            for M in Ms:
                if M > L:
                    continue
                sb, sizes = subbars(rw, M)
                pb, _ = subbars(pw, M)
                rv = (sb ** 2).sum(axis=1)
                q = quart_suite(sb, M)
                trq, trv = q["TRQ3_TRV3"]
                rq = q["RQ_RV"][0]
                logrv = np.log(np.maximum(rv, 1e-300))
                nonfinite_log = int((rv <= 0).sum())
                eff = (pb > 0).sum(axis=1)          # sub-bars with data
                first_share = np.divide(sb[:, 0] ** 2, np.maximum(rv, 1e-300))
                last_share = np.divide(sb[:, -1] ** 2, np.maximum(rv, 1e-300))
                np.savez_compressed(
                    os.path.join(CACHE,
                                 f"grid_{root}_{geom}_{btag}_{hname}_M{M}.npz"),
                    rv=rv, trv=trv, rq=rq, trq=trq,
                    logrv=logrv, eff=eff.astype(np.int16),
                    first_share=first_share.astype(np.float32),
                    last_share=last_share.astype(np.float32),
                    years=np.repeat(yrs, nw))
                grid_rows.append(dict(
                    root=root, geom=geom, btag=btag, horizon=hname, M=M,
                    session_minutes=SESSION_MIN[(geom, hname)],
                    L_returns_per_window=int(L),
                    M_divides_session=bool(SESSION_MIN[(geom, hname)] % M == 0),
                    M_divides_L=bool(L % M == 0),
                    subbar_size_min=int(sizes.min()),
                    subbar_size_max=int(sizes.max()),
                    n_stub_subbars=int((sizes != sizes.max()).sum()),
                    n_windows=int(len(rv)),
                    var_log_rv=float(logrv.var()),
                    n_nonfinite_log=nonfinite_log,
                    share_full_M=float((eff == M).mean()),
                    share_below_0p9M=float((eff < 0.9 * M).mean()),
                    mean_eff_M=float(eff.mean()),
                    mean_first_share=float(first_share.mean()),
                    mean_last_share=float(last_share.mean()),
                    trigamma_M_over_2=float(trigamma(M / 2.0)),
                    two_over_M=2.0 / M,
                    mean_trv_over_rv=float(
                        (trv / np.maximum(rv, 1e-300)).mean())))
    pd.DataFrame(grid_rows).to_csv(
        os.path.join(RES, "phase4_grid_index.csv"), index=False)
    timers["p4_grid_cache"] = round(time.time() - t, 1)

    size = sum(os.path.getsize(os.path.join(CACHE, f))
               for f in os.listdir(CACHE))
    timers["total"] = round(time.time() - t0, 1)
    with open(os.path.join(RES, "phase34_timers.json"), "w") as fh:
        json.dump(dict(timers=timers, cache_bytes=size,
                       cache_files=len(os.listdir(CACHE))), fh, indent=1)
    print(json.dumps(timers, indent=1))
    print(f"cache: {len(os.listdir(CACHE))} files, {size/1e6:.1f} MB")


if __name__ == "__main__":
    main()
